# Generated by Django 4.2.16 on 2024-12-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commonuser",
            name="default_search_radius",
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name="commonuser",
            name="default_zip_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="sport_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("soccer", "Soccer"),
                    ("basketball", "Basketball"),
                    ("tennis", "Tennis"),
                    ("volleyball", "Volleyball"),
                    ("football", "Football"),
                    ("baseball", "Baseball"),
                    ("other", "Other"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
    ]
