# Generated by Django 4.2.16 on 2024-12-03 02:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sports", "0002_commonuser_default_search_radius_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commonuser",
            name="default_search_radius",
        ),
        migrations.RemoveField(
            model_name="commonuser",
            name="default_zip_code",
        ),
    ]
