# Generated by Django 4.2.16 on 2024-12-03 02:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sports", "0003_remove_commonuser_default_search_radius_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectfile",
            name="keywords",
        ),
    ]
